/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        unbounded: ['Unbounded', 'sans-serif'],
        chivo: ['Chivo', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'space-grotesk': ['Space Grotesk', 'sans-serif'],
        'label-caps': ['Space Grotesk', 'sans-serif'],
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'stats-num': ['Space Grotesk', 'sans-serif'],
        'body-base': ['Inter', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#131313",
        "on-background": "#e5e2e1",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#ffffff",
          fixed: "#c3f400",
          fixed_dim: "#abd600",
          container: "#c3f400",
          foreground: "#283500",
        },
        tertiary: {
          fixed: "#7df4ff",
          fixed_dim: "#00dbe9",
          container: "#7df4ff",
          fixed_variant: "#004f54",
        },
        secondary: {
          DEFAULT: "#ffb59e",
          container: "#ff571a",
          fixed: "#ffdbd0",
          fixed_dim: "#ffb59e",
        },
        surface: {
          DEFAULT: "#131313",
          dim: "#131313",
          container: "#201f1f",
          "container-low": "#1c1b1b",
          "container-high": "#2a2a2a",
          "container-highest": "#353534",
          "container-lowest": "#0e0e0e",
          variant: "#353534",
          bright: "#393939",
          tint: "#abd600",
        },
        on: {
          primary: "#283500",
          "primary-container": "#556d00",
          secondary: "#5e1700",
          "secondary-container": "#521300",
          "secondary-fixed": "#3a0b00",
          "secondary-fixed-variant": "#852400",
          tertiary: "#00363a",
          "tertiary-container": "#006f77",
          "tertiary-fixed": "#002022",
          surface: "#e5e2e1",
          "surface-variant": "#c4c9ac",
          error: "#690005",
          "error-container": "#ffdad6",
        },
        error: {
          DEFAULT: "#ffb4ab",
          container: "#93000a",
        },
        outline: "#8e9379",
        "outline-variant": "#444933",
        inverse: {
          surface: "#e5e2e1",
          primary: "#506600",
          "on-surface": "#313030",
        },
        neon: {
          green: "#22c55e",
          cyan: "#06b6d4",
        },
        void: "#09090b",
        "primary-fixed": "#c3f400",
        "tertiary-fixed": "#7df4ff",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        'neon': '0 0 20px rgba(34, 197, 94, 0.3)',
        'neon-cyan': '0 0 20px rgba(6, 182, 212, 0.3)',
        'void': '0 20px 40px -10px rgba(0,0,0,0.8)',
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "pulse-neon": "pulse-neon 2s ease-in-out infinite",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "pulse-neon": {
          "0%, 100%": { boxShadow: "0 0 20px rgba(34, 197, 94, 0.3)" },
          "50%": { boxShadow: "0 0 40px rgba(34, 197, 94, 0.6)" },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
